#!/usr/bin/env python3

from __future__ import annotations

import re
import sys
from pathlib import Path


def parse_colors(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    pattern = re.compile(r'^\s*([A-Za-z0-9_]+)\s*=\s*"?(#[0-9A-Fa-f]{6})"?')
    for line in path.read_text().splitlines():
        match = pattern.match(line)
        if match:
            data[match.group(1)] = match.group(2).lower()
    return data


def hex_to_rgb(value: str) -> tuple[int, int, int]:
    value = value.lstrip("#")
    return tuple(int(value[i : i + 2], 16) for i in (0, 2, 4))


def rgb_to_hex(rgb: tuple[int, int, int]) -> str:
    return "#{:02x}{:02x}{:02x}".format(*rgb)


def rgba(color: str, alpha: str) -> str:
    red, green, blue = hex_to_rgb(color)
    return f"rgba({red}, {green}, {blue}, {alpha})"


def mix(left: str, right: str, amount: float) -> str:
    l_rgb = hex_to_rgb(left)
    r_rgb = hex_to_rgb(right)
    return rgb_to_hex(
        tuple(round(l_rgb[i] * (1 - amount) + r_rgb[i] * amount) for i in range(3))
    )


def luminance(color: str) -> float:
    rgb = [channel / 255 for channel in hex_to_rgb(color)]
    linear = [
        channel / 12.92
        if channel <= 0.04045
        else ((channel + 0.055) / 1.055) ** 2.4
        for channel in rgb
    ]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


def require(colors: dict[str, str], key: str) -> str:
    if key not in colors:
        raise SystemExit(f"Missing {key} in colors file")
    return colors[key]


def build_css(colors: dict[str, str]) -> str:
    bg = require(colors, "background")
    fg = require(colors, "foreground")
    accent = colors.get("accent", colors.get("color4", fg))
    muted = colors.get("color8", mix(bg, fg, 0.42))
    red = colors.get("color1", accent)
    yellow = colors.get("color3", accent)
    cyan = colors.get("color6", accent)

    light = luminance(bg) > 0.55
    contrast = "#000000" if light else "#ffffff"
    shade = "#000000" if light else "#ffffff"

    base = mix(bg, contrast, 0.04 if light else 0.03)
    surface = mix(bg, contrast, 0.08 if light else 0.07)
    surface_alt = mix(bg, contrast, 0.14 if light else 0.12)
    hover = mix(bg, contrast, 0.20 if light else 0.18)
    border = mix(bg, fg, 0.24 if light else 0.22)
    body = mix(fg, bg, 0.18)
    shadow = "rgba(0, 0, 0, 0.20)" if light else "rgba(0, 0, 0, 0.72)"
    panel_alpha = "0.38" if light else "0.42"
    panel_rounding = "4px"

    return f"""/* Generated by ~/.config/swaync/generate-theme.py from current theme colors. */
* {{
  all: unset;
  font-size: 14px;
  font-family: "Ubuntu Nerd Font";
  transition: 200ms;
}}

trough highlight {{
  background: {accent};
}}

scale {{
  margin: 0 7px;
}}

scale trough {{
  margin: 0rem 1rem;
  min-height: 8px;
  min-width: 70px;
  border-radius: 12.6px;
}}

trough slider {{
  margin: -10px;
  border-radius: 12.6px;
  box-shadow: 0 0 2px {shadow};
  transition: all 0.2s ease;
  background-color: {accent};
}}

trough slider:hover {{
  box-shadow:
    0 0 2px {shadow},
    0 0 8px {accent};
}}

trough {{
  background-color: {surface_alt};
}}

/* notifications */
.notification-background {{
  box-shadow:
    0 0 8px 0 {shadow},
    inset 0 0 0 1px {border};
  border-radius: 12.6px;
  margin: 18px;
  background: {surface};
  color: {fg};
  padding: 0;
}}

.notification-background .notification {{
  padding: 7px;
  border-radius: 12.6px;
}}

.notification-background .notification.critical {{
  box-shadow: inset 0 0 7px 0 {red};
}}

.notification .notification-content {{
  margin: 7px;
}}

.notification-content .summary {{
  color: {fg};
}}

.notification-content .time {{
  color: {muted};
}}

.notification-content .body {{
  color: {body};
}}

.notification > *:last-child > * {{
  min-height: 3.4em;
}}

.notification-background .close-button {{
  margin: 7px;
  padding: 2px;
  border-radius: 6.3px;
  color: {bg};
  background-color: {red};
}}

.notification-background .close-button:hover {{
  background-color: {mix(red, fg, 0.18)};
}}

.notification-background .close-button:active {{
  background-color: {mix(red, fg, 0.32)};
}}

.notification .notification-action {{
  border-radius: 7px;
  color: {fg};
  box-shadow: inset 0 0 0 1px {border};
  margin: 4px;
  padding: 8px;
  font-size: 0.2rem; /* controls the button size not text size*/
  background-color: {surface_alt};
}}

.notification .notification-action:hover {{
  background-color: {hover};
}}

.notification .notification-action:active {{
  background-color: {mix(hover, shade, 0.08)};
}}

.notification.critical progress {{
  background-color: {red};
}}

.notification.low progress,
.notification.normal progress {{
  background-color: {accent};
}}

.notification progress,
.notification trough,
.notification progressbar {{
  border-radius: 12.6px;
  padding: 3px 0;
}}

/* control center */
.control-center {{
  box-shadow:
    0 12px 35px 0 {"rgba(0, 0, 0, 0.18)" if light else "rgba(0, 0, 0, 0.42)"},
    inset 0 0 0 1px {rgba(border, "0.42" if not light else "0.36")};
  border-radius: {panel_rounding};
  background: {rgba(base, panel_alpha)};
  color: {fg};
  padding: 14px;
}}

.control-center .notification-background {{
  border-radius: 7px;
  box-shadow: inset 0 0 0 1px {border};
  margin: 4px 10px;
}}

.control-center .notification-background .notification {{
  border-radius: 7px;
}}

.control-center .notification-background .notification.low {{
  opacity: 0.8;
}}

.control-center .widget-title > label {{
  color: {fg};
  font-size: 1.3em;
}}

.control-center .widget-title button {{
  border-radius: 7px;
  color: {fg};
  background-color: {surface_alt};
  box-shadow: inset 0 0 0 1px {border};
  padding: 8px;
}}

.control-center .widget-title button:hover {{
  background-color: {hover};
}}

.control-center .widget-title button:active {{
  background-color: {mix(hover, shade, 0.08)};
}}

.control-center .notification-group {{
  margin-top: 10px;
}}

.control-center .notification-group:focus .notification-background {{
  background-color: {surface_alt};
}}

scrollbar slider {{
  margin: -3px;
  opacity: 0.8;
}}

scrollbar trough {{
  margin: 2px 0;
}}

/* dnd */
.widget-dnd {{
  margin-top: 5px;
  border-radius: 8px;
  font-size: 1.1rem;
}}

.widget-dnd > switch {{
  font-size: initial;
  border-radius: 8px;
  background: {surface_alt};
  box-shadow: none;
}}

.widget-dnd > switch:checked {{
  background: {accent};
}}

.widget-dnd > switch slider {{
  background: {border};
  border-radius: 8px;
}}

/* mpris */
.widget-mpris-player {{
  background: {rgba(surface_alt, "0.48")};
  border-radius: 18px;
  color: {fg};
}}

.mpris-overlay {{
  background-color: {rgba(surface_alt, "0.55")};
  opacity: 1;
  padding: 15px 10px;
}}

.widget-mpris-album-art {{
  -gtk-icon-size: 100px;
  border-radius: 12.6px;
  margin: 0 10px;
}}

.widget-mpris-title {{
  font-size: 1.2rem;
  color: {fg};
}}

.widget-mpris-subtitle {{
  font-size: 1rem;
  color: {body};
}}

.widget-mpris button {{
  border-radius: 12.6px;
  color: {fg};
  margin: 0 5px;
  padding: 2px;
}}

.widget-mpris button image {{
  -gtk-icon-size: 1.8rem;
}}

.widget-mpris button:hover {{
  background-color: {hover};
}}

.widget-mpris button:active {{
  background-color: {mix(hover, shade, 0.08)};
}}

.widget-mpris button:disabled {{
  opacity: 0.5;
}}

.widget-menubar > box > .menu-button-bar > button > label {{
  font-size: 3rem;
  padding: 0.5rem 2rem;
}}

.widget-menubar > box > .menu-button-bar > :last-child {{
  color: {red};
}}

.power-buttons button:hover,
.powermode-buttons button:hover,
.screenshot-buttons button:hover {{
  background: {hover};
}}

.control-center .widget-label > label {{
  color: {fg};
  font-size: 2rem;
}}

.widget-buttons-grid {{
  padding-top: 0;
}}

.widget-buttons-grid > flowbox > flowboxchild {{
  min-width: 0;
}}

.widget-buttons-grid > flowbox > flowboxchild > button label {{
  font-size: 0.95rem;
  font-weight: 600;
  min-width: 0;
  text-align: center;
}}

.widget-buttons-grid > flowbox > flowboxchild > button {{
  min-width: 154px;
  min-height: 66px;
  border-radius: 18px;
  margin: 4px;
  padding: 0 10px;
  color: {fg};
  background: {rgba(surface_alt, "0.48")};
  box-shadow: inset 0 0 0 1px {rgba(border, "0.38")};
}}

.widget-buttons-grid > flowbox > flowboxchild > button:hover {{
  background: {rgba(hover, "0.58")};
}}

.widget-buttons-grid > flowbox > flowboxchild > button.toggle:checked {{
  color: {bg};
  background: {rgba(accent, "0.78")};
}}

.widget-volume {{
  padding: 1rem 0;
  border-radius: 18px;
  background: {rgba(surface_alt, "0.38")};
}}

.widget-volume label {{
  color: {fg};
  padding: 0 1rem;
}}

.widget-volume trough highlight {{
  background: {cyan};
}}

.widget-backlight trough highlight {{
  background: {yellow};
}}

.widget-backlight label {{
  font-size: 1.5rem;
  color: {yellow};
}}

.widget-backlight .KB {{
  padding-bottom: 1rem;
}}

.image {{
  padding-right: 0.5rem;
}}

.widget-title,
.widget-dnd,
.widget-mpris,
.widget-volume,
.widget-buttons-grid,
.widget-notifications {{
  margin: 0 0 10px 0;
}}

.notification .notification-content overlay {{
  min-width: 30px;
  min-height: 30px;
  margin: 6px;
  -gtk-icon-size: 30px;
}}
"""


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: generate-theme.py <colors.toml> <output.css>", file=sys.stderr)
        return 2

    colors_path = Path(sys.argv[1]).expanduser()
    output_path = Path(sys.argv[2]).expanduser()
    colors = parse_colors(colors_path)

    if output_path.is_symlink():
        output_path.unlink()

    output_path.write_text(build_css(colors))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
