name = "ai-tools"
name_pretty = "AI"
parent = "development"
icon = ""
fixed_order = true

[[entries]]
text = "Claude"
subtext = ">"
icon = "󰚩"
submenu = "ai-claude"

[[entries]]
text = "Codex"
subtext = ">"
icon = ""
submenu = "ai-codex"
