name = "aws-profiles"
name_pretty = "AWS"
parent = "cloud"
icon = ""
fixed_order = true

[[entries]]
text = "Development"
subtext = ">"
keywords = ["doola-dev"]
icon = ""
submenu = "aws-development"

[[entries]]
text = "Production"
subtext = ">"
keywords = ["doola-prod"]
icon = ""
submenu = "aws-production"
