name = "capture"
name_pretty = "Capture"
parent = "main"
icon = ""
fixed_order = true

[[entries]]
text = "Color"
keywords = ["picker", "hyprpicker"]
icon = "󰈊"
actions = { "open" = "sh -c 'sleep 0.2 && hyprpicker -a'" }

[[entries]]
text = "OCR text"
keywords = ["text", "ocr", "tesseract"]
icon = "󰴑"
actions = { "open" = "$HOME/.config/walker/scripts/actions/capture/text.sh" }

[[entries]]
text = "QR code"
keywords = ["qr", "barcode"]
icon = "󰐲"
actions = { "open" = "$HOME/.config/walker/scripts/actions/capture/qr.sh" }

[[entries]]
text = "Screenrecord"
subtext = ">"
keywords = ["record", "video"]
icon = ""
submenu = "screenrecord"

[[entries]]
text = "Screenshot"
subtext = ">"
icon = "󰄀"
submenu = "screenshot"

[[entries]]
text = "Transcode"
keywords = ["convert", "compress", "image", "video"]
icon = "󰑕"
actions = { "open" = "$HOME/.config/walker/scripts/actions/capture/transcode.sh" }
