name = "cloud"
name_pretty = "Cloud"
parent = "development"
icon = ""
fixed_order = true

[[entries]]
text = "AWS"
subtext = ">"
keywords = ["amazon"]
icon = ""
submenu = "aws-profiles"

[[entries]]
text = "Azure"
subtext = ">"
keywords = ["microsoft cloud"]
icon = "󰠅"
submenu = "azure"

[[entries]]
text = "GCP"
subtext = ">"
keywords = ["google cloud"]
icon = ""
submenu = "gcp"
