name = "gaming"
name_pretty = "Gaming"
parent = "main"
icon = "󰊴"
fixed_order = true

[[entries]]
text = "Steam"
icon = ""
actions = { open = "python3 $HOME/.config/walker/scripts/actions/install/software.py gaming steam" }

[[entries]]
text = "GeForce NOW"
subtext = "Cloud gaming · requires account and supported hardware/network"
icon = "󰊴"
actions = { open = "python3 $HOME/.config/walker/scripts/actions/install/software.py gaming geforcenow" }
