name = "grafana-logs"
name_pretty = "Grafana Logs"
parent = "development"
icon = "󰨇"
fixed_order = true

[[entries]]
text = "Development"
subtext = "doola-dev"
icon = "󰨇"
actions = { "open" = "$HOME/.config/walker/scripts/menus/cloud/aws/grafana.sh doola-dev" }

[[entries]]
text = "Production"
subtext = "doola-prod"
icon = "󰨇"
actions = { "open" = "$HOME/.config/walker/scripts/menus/cloud/aws/grafana.sh doola-prod" }
