name = "learn"
name_pretty = "Learn"
parent = "main"
icon = "󰧑"
fixed_order = true

[[entries]]
text = "LazyVim Commands"
keywords = ["lazyvim", "vim", "nvim", "neovim", "commands"]
icon = ""
actions = { "open" = "$HOME/.config/walker/scripts/menus/vim.sh" }

[[entries]]
text = "Mouse Gestures"
keywords = ["mouse", "click", "double", "drag", "wallpaper", "theme", "bar"]
icon = "󰍽"
actions = { "open" = "$HOME/.config/walker/scripts/menus/mouse-gestures.sh" }

[[entries]]
text = "Shortcuts"
keywords = ["keybinds", "keys", "hotkeys"]
icon = "󰌌"
actions = { "open" = "$HOME/.config/walker/scripts/menus/shortcuts.sh" }

[[entries]]
text = "Tmux Commands"
keywords = ["tmux", "terminal", "multiplexer", "session", "panes"]
icon = ""
actions = { "open" = "$HOME/.config/walker/scripts/menus/tmux.sh" }
