name = "security"
name_pretty = "Security"
parent = "system"
icon = "󰒃"
fixed_order = true

[[entries]]
text = "Update Password"
icon = "󰌾"
actions = { open = "kitty --hold -e python3 $HOME/.config/walker/scripts/actions/system/security.py password" }

[[entries]]
text = "Fingerprint"
icon = "󰈷"
submenu = "fingerprint"

[[entries]]
text = "FIDO2 Security Key"
icon = "󰌆"
submenu = "fido2"

[[entries]]
text = "Return to Password Authentication"
icon = "󰌾"
actions = { open = "kitty --hold -e python3 $HOME/.config/walker/scripts/actions/system/security.py password-only" }
