name = "style"
name_pretty = "Style"
parent = "main"
icon = ""
fixed_order = true

[[entries]]
text = "Theme"
subtext = ">"
keywords = ["colors", "appearance"]
icon = "󰸌"
submenu = "theme"

[[entries]]
text = "Wallpaper"
subtext = ">"
keywords = ["background"]
icon = "🖻"
submenu = "wallpaper"

[[entries]]
text = "Lockscreen"
subtext = ">"
keywords = ["lock", "screen", "security"]
icon = "󰌾"
submenu = "lockscreen"

[[entries]]
text = "Workspaces"
subtext = ">"
keywords = ["numbers", "glyph", "dots", "bar"]
icon = "󰍹"
submenu = "workspaces"
