name = "update"
name_pretty = "Update"
parent = "system"
icon = ""
fixed_order = true

[[entries]]
text = "Advanced"
subtext = ">"
icon = "󰒓"
submenu = "update-advanced"

[[entries]]
text = "System Update"
icon = "󰜉"
actions = { open = "kitty --hold -e bash $HOME/.config/walker/scripts/actions/system/update.sh system" }
