const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const model = {};
vm.createContext(model);
vm.runInContext(fs.readFileSync(`${__dirname}/../WorkspaceModel.js`, 'utf8').replace('.pragma library', ''), model);
assert.equal(model.ceiling([], 1), 5);
assert.equal(model.ceiling([{id: 7}], 3), 7);
assert.equal(model.ceiling([], 10), 10);
assert.equal(model.ceiling([{id: 99}, {id: -99}], 1), 10);
const window = (id, info = {}) => ({workspace: {id}, lastIpcObject: info, monitor: {name: 'Monitor'}});
const occupied = model.occupied([window(3), window(1), window(3), window(2, {mapped: false}), window(4, {hidden: true}), window(-99), window(11), {}]);
assert.equal(JSON.stringify(occupied.map(w => [w.id, w.windows.length])), '[[1,1],[3,2]]');
assert.equal(model.ceiling(model.occupied([window(5)]), 8), 8, 'visiting empty 8 shows sequential 1–8');
assert.equal(model.ceiling(model.occupied([window(5)]), 5), 5, 'leaving empty 8 removes extra markers');
assert.equal(model.ceiling(model.occupied([window(7)]), 5), 7, 'occupied 7 keeps sequential 1–7');
assert.equal(model.ceiling(model.occupied([window(7), window(8)]), 5), 8);
assert.equal(model.ceiling(model.occupied([window(7)]), 5), 7, 'closing last window on 8 shrinks to 7');
const bounds = model.bounds([window(1, {at: [-200, 40], size: [100, 100]}), window(1, {at: [0, 40], size: [200, 100]})]);
assert.equal(JSON.stringify(bounds), '{"x":-200,"y":40,"width":400,"height":100}');
assert.equal(model.bounds([]).width, 1);
const desktop = {windows: [{monitor: {lastIpcObject: {width: 2560, height: 1080, scale: 1, x: -2560, y: 0}}}]};
assert.equal(JSON.stringify(model.frame(desktop)), '{"x":-2560,"y":0,"width":2560,"height":1080}');
desktop.windows[0].monitor.lastIpcObject = {width: 3840, height: 2160, scale: 2, transform: 1};
assert.equal(model.frame(desktop).width, 1080);
assert.equal(model.frame(desktop).height, 1920);
assert.equal(model.selection(0, 'left', 2, 3), 0);
assert.equal(model.selection(0, 'right', 2, 3), 1);
assert.equal(model.selection(0, 'down', 2, 3), 2);
assert.equal(model.selection(2, 'up', 2, 3), 0);
assert.equal(model.selection(2, 'down', 2, 3), 2);
assert.equal(model.selection(0, 'right', 2, 0), -1);
assert.deepEqual(JSON.parse(JSON.stringify(model.focusCommand(3))), ['hyprctl', 'dispatch', 'hl.dsp.focus({ workspace = 3 })']);
assert.equal(model.focusCommand(0).length, 0);
assert.equal(model.focusCommand(11).length, 0);
assert.equal(model.focusCommand('2; rm').length, 0);
console.log('Workspace model: defaults, sequential ceiling, cap, occupied-only groups, geometry passed');
