env = GTK_THEME,Adwaita-dark
env = ADW_DEBUG_COLOR_SCHEME,prefer-dark

env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_STYLE_OVERRIDE,kvantum

env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24
