#!/usr/bin/env python3
"""Center-out wallpaper reveal with atomic persistence and Hyprpaper fallback."""
import argparse
import fcntl
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile


def runtime():
    root = Path(os.environ.get("XDG_RUNTIME_DIR", str(Path.home() / ".cache"))) / "eitr-wallpaper"
    root.mkdir(parents=True, mode=0o700, exist_ok=True)
    return root


WALLPAPER_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp"}


def wallpapers(directory):
    """Return a theme's wallpapers in natural order (like `sort -V`)."""
    def natural(path):
        return [int(part) if part.isdigit() else part.lower()
                for part in re.split(r"(\d+)", str(path.relative_to(directory)))]
    directory = Path(directory)
    if not directory.is_dir():
        return []
    files = (path for path in directory.rglob("*")
             if path.is_file() and path.suffix.lower() in WALLPAPER_SUFFIXES)
    return sorted(files, key=natural)


def snapshot():
    previous = Path.home() / ".cache/current-wallpaper-image"
    if not previous.is_file():
        return ""
    descriptor, name = tempfile.mkstemp(prefix="previous-", suffix=previous.resolve().suffix, dir=runtime())
    os.close(descriptor)
    shutil.copyfile(previous, name)
    return name


def commit(path):
    path = str(Path(path).resolve(strict=True))
    monitors = json.loads(subprocess.check_output(["hyprctl", "monitors", "-j"], text=True))
    for monitor in monitors:
        subprocess.run(["hyprctl", "hyprpaper", "wallpaper", monitor["name"] + "," + path], check=True)
    cache = Path.home() / ".cache"
    cache.mkdir(parents=True, exist_ok=True)
    temporary = cache / "current-wallpaper-image.new"
    temporary.unlink(missing_ok=True)
    temporary.symlink_to(path)
    temporary.replace(cache / "current-wallpaper-image")
    listing = cache / "current-wallpaper.new"
    listing.write_text(path + "\n")
    listing.replace(cache / "current-wallpaper")


def apply(path, previous=None):
    path = str(Path(path).resolve(strict=True))
    with (runtime() / "transition.lock").open("w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        previous = previous or snapshot()
        # Only remove the temporary image generated by this helper.
        owned = bool(previous and Path(previous).parent == runtime() and Path(previous).name.startswith("previous-"))
        committed = False
        try:
            env = dict(os.environ, EITR_PREVIOUS_WALLPAPER=Path(previous).as_uri() if previous else "",
                       EITR_NEXT_WALLPAPER=Path(path).as_uri())
            config = Path.home() / ".config/quickshell/wallpaper-transition"
            subprocess.run(["quickshell", "-p", str(config)], env=env, check=True, timeout=15)
            committed = True
        except (OSError, subprocess.SubprocessError):
            pass
        finally:
            try:
                # Successful QML already committed underneath the transition.
                # Reapplying after removing the layer can cause another flash.
                if not committed:
                    commit(path)
            finally:
                if owned:
                    Path(previous).unlink(missing_ok=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("action", choices=["snapshot", "apply", "commit", "list"])
    parser.add_argument("path", nargs="?")
    parser.add_argument("--previous")
    args = parser.parse_args()
    if args.action == "snapshot":
        print(snapshot())
    elif args.action == "list":
        for wallpaper in wallpapers(args.path or Path.home() / ".config/theme/current/backgrounds"):
            print(wallpaper)
    elif args.action == "commit":
        from urllib.parse import unquote, urlparse
        commit(unquote(urlparse(args.path).path) if args.path.startswith("file:") else args.path)
    else:
        apply(args.path, args.previous)
